# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formly', '0002_add_expected_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='expected_answers',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.IntegerField(choices=[(0, 'Free Response - One Line'), (1, 'Free Response - Box'), (2, 'Multiple Choice - Pick One'), (4, 'Multiple Choice - Pick One (Dropdown)'), (5, 'Multiple Choice - Can select multiple answers'), (3, 'Date'), (6, 'File Upload'), (7, 'True/False'), (8, 'Multiple Free Responses - Single Lines')]),
        ),
        migrations.AlterField(
            model_name='fieldresult',
            name='answer',
            field=jsonfield.fields.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='fieldresult',
            name='upload',
            field=models.FileField(blank=True, upload_to='formly/'),
        ),
    ]
