# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formly', '0003_auto_20160816_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikertChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LikertScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.IntegerField(choices=[(0, 'Free Response - One Line'), (1, 'Free Response - Box'), (2, 'Multiple Choice - Pick One'), (4, 'Multiple Choice - Pick One (Dropdown)'), (5, 'Multiple Choice - Can select multiple answers'), (3, 'Date'), (6, 'File Upload'), (7, 'True/False'), (8, 'Multiple Free Responses - Single Lines'), (9, 'Likert Scale')]),
        ),
        migrations.AddField(
            model_name='likertchoice',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='formly.LikertScale'),
        ),
        migrations.AlterUniqueTogether(
            name='likertchoice',
            unique_together=set([('scale', 'label'), ('scale', 'score')]),
        ),
    ]
