# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formly', '0005_field_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='scale',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formly.LikertScale'),
        ),
    ]
