# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-09 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formly', '0007_help_text_and_label_to_textfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikertChoice',
            new_name='OrdinalChoice',
        ),
        migrations.RenameModel(
            old_name='LikertScale',
            new_name='OrdinalScale',
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.IntegerField(choices=[(0, 'Free Response - One Line'), (1, 'Free Response - Box'), (2, 'Multiple Choice - Pick One'), (4, 'Multiple Choice - Pick One (Dropdown)'), (5, 'Multiple Choice - Can select multiple answers'), (3, 'Date'), (6, 'File Upload'), (7, 'True/False'), (8, 'Multiple Free Responses - Single Lines'), (9, 'Likert Scale'), (10, 'Rating Scale')]),
        ),
    ]
