# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-12 23:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formly', '0011_field_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='mapping',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fieldresult',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
