# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-07 22:49
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('formly', '0013_auto_20170914_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='mapping',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='fieldresult',
            name='answer',
            field=jsonfield.fields.JSONField(blank=True),
        ),
    ]
